# Generated by Django 5.0 on 2024-04-13 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customuser_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='activated',
        ),
        migrations.AddField(
            model_name='customuser',
            name='verified_user',
            field=models.BooleanField(default=False),
        ),
    ]
