# Generated by Django 5.0 on 2024-04-13 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_customuser_activated_customuser_verified_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='verified_user',
        ),
    ]
